/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as PharmacyVerifyIdRouteImport } from './routes/pharmacy.verify.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyVerifyIdRoute = PharmacyVerifyIdRouteImport.update({
  id: '/pharmacy/verify/$id',
  path: '/pharmacy/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRoute
  '/patient': typeof PatientRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/pharmacy/verify/$id': typeof PharmacyVerifyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRoute
  '/patient': typeof PatientRoute
  '/pharmacy': typeof PharmacyIndexRoute
  '/pharmacy/verify/$id': typeof PharmacyVerifyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRoute
  '/patient': typeof PatientRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/pharmacy/verify/$id': typeof PharmacyVerifyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/doctor'
    | '/patient'
    | '/pharmacy/'
    | '/pharmacy/verify/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/doctor'
    | '/patient'
    | '/pharmacy'
    | '/pharmacy/verify/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/doctor'
    | '/patient'
    | '/pharmacy/'
    | '/pharmacy/verify/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DoctorRoute: typeof DoctorRoute
  PatientRoute: typeof PatientRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
  PharmacyVerifyIdRoute: typeof PharmacyVerifyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/verify/$id': {
      id: '/pharmacy/verify/$id'
      path: '/pharmacy/verify/$id'
      fullPath: '/pharmacy/verify/$id'
      preLoaderRoute: typeof PharmacyVerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DoctorRoute: DoctorRoute,
  PatientRoute: PatientRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
  PharmacyVerifyIdRoute: PharmacyVerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
